### ISSUE TITLE
Task 2 (Mockups)

### ISSUE THREAD

**Issue by ala-n** [cfif985/insta#2]
[-] Filter fields are not described (both behaviour and visually)
[-] (9-10) Tag field should be described detailed
[-] (Minor) What does the symbol with two arrows mean? (in the right bottom corner of the post area). 
[-] "Invalid password" state is missing
[-] In edit mode date and username field shouldn't be editable
[-] Also User should be able to switch view between his posts and the whole feed.

Current mark 6 (with **-**)

**Comment by cfif985** [comment]
У меня есть 3 и 4 задание
